export const INIT_LOGIN = 'INIT_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const INIT_LOGOUT = 'INIT_LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const INIT_AUTH_STATUS = 'INIT_AUTH_STATUS';
export const AUTH_STATUS_SUCCESS = 'AUTH_STATUS_SUCCESS';
export const AUTH_STATUS_FAILURE = 'AUTH_STATUS_FAILURE';

export const INIT_SIGNUP = 'INIT_SIGNUP';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const GET_USER_DETAIL = 'GET_USER_DETAIL';
export const PUT_USER_DETAIL = 'PUT_USER_DETAIL';

export const GET_UPCOMING_BOOKINGS = 'GET_UPCOMING_BOOKINGS';
export const PUT_UPCOMING_BOOKINGS = 'PUT_UPCOMING_BOOKINGS';

export const GET_MY_BOOKINGS = 'GET_MY_BOOKINGS';
export const PUT_MY_BOOKINGS = 'PUT_MY_BOOKINGS';

export const GET_MESSAGES = 'GET_MESSAGES';
export const PUT_MESSAGES = 'PUT_MESSAGES';

export const GET_MESSAGE_DETAILS = 'GET_MESSAGE_DETAILS';
export const PUT_MESSAGE_DETAILS = 'PUT_MESSAGE_DETAILS';

export const GET_USER_DETAIL_PROFILE = 'GET_USER_DETAIL_PROFILE';
export const PUT_USER_DETAIL_PROFILE = 'PUT_USER_DETAIL_PROFILE';

export const INIT_CHANGE_PASSWORD = 'INIT_CHANGE_PASSWORD';
export const SUCCESS_CHANGE_PASSWORD = 'SUCCESS_CHANGE_PASSWORD';

export const GET_ALL_TRANSACTIONS = 'GET_ALL_TRANSACTIONS';
export const PUT_ALL_TRANSACTIONS = 'PUT_ALL_TRANSACTIONS';

export const GET_COLLATERALS = 'GET_COLLATERALS';
export const PUT_COLLATERALS = 'PUT_COLLATERALS';

export const GET_TYPES = 'GET_TYPES';
export const PUT_TYPES = 'PUT_TYPES';

export const SUBMIT_SERVICE_REQUEST = 'SUBMIT_SERVICE_REQUEST';
export const SUBMIT_SERVICE_REQUEST_SUCCESS = 'SUBMIT_SERVICE_REQUEST_SUCCESS';
export const SUBMIT_SERVICE_REQUEST_FAILURE = 'SUBMIT_SERVICE_REQUEST_FAILURE';

export const GET_MY_LATEST_TASK = 'GET_MY_LATEST_TASK';
export const PUT_MY_LATEST_TASK = 'PUT_MY_LATEST_TASK';

export const GET_TASK_DETAILS = 'GET_TASK_DETAILS';
export const PUT_TASK_DETAILS = 'PUT_TASK_DETAILS';

export const ACCEPT_REQUEST = 'ACCEPT_REQUEST';
export const ACCEPT_REQUEST_SUCCESS = 'ACCEPT_REQUEST_SUCCESS';

export const GET_ORDERLIST = 'GET_ORDERLIST';
export const PUT_ORDERLIST = 'PUT_ORDERLIST';

export const GET_MYPAWNS = 'GET_MYPAWNS';
export const PUT_MYPAWNS = 'PUT_MYPAWNS';

export const CANCEL_MYPAWNS = 'CANCEL_MYPAWNS';
export const CANCEL_CONFIRMED_MYPAWNS = 'CANCEL_CONFIRMED_MYPAWNS';

export const GET_PAWNDETAILS = 'GET_PAWNDETAILS';
export const PUT_PAWNDETAILS = 'PUT_PAWNDETAILS';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const PUT_PRODUCTS = 'PUT_PRODUCTS';

export const GET_PROVIDER_DASHBOARD_DATA = 'GET_PROVIDER_DASHBOARD_DATA';
export const PUT_PROVIDER_DASHBOARD_DATA = 'PUT_PROVIDER_DASHBOARD_DATA';

export const GET_PRODUCT_DETAILS = 'GET_PRODUCT_DETAILS';
export const PUT_PRODUCT_DETAILS = 'PUT_PRODUCT_DETAILS';

export const PROCEED_TO_PURCHASE = 'PROCEED_TO_PURCHASE';
export const PURCHASE_SUCCESS = 'PURCHASE_SUCCESS';
export const PURCHASE_FAILURE = 'PURCHASE_FAILURE';

export const PROCEED_TO_ACCEPT = 'PROCEED_TO_ACCEPT';
export const ACCEPT_SUCCESS = 'ACCEPT_SUCCESS';
export const ACCEPT_FAILURE = 'ACCEPT_FAILURE';

export const GET_ORDER_LIST = 'GET_ORDER_LIST';
export const PUT_ORDER_LIST = 'PUT_ORDER_LIST';

export const GET_NEW_PAWNS_LIST = 'GET_NEW_PAWNS_LIST';
export const PUT_NEW_PAWNS_LIST = 'PUT_NEW_PAWNS_LIST';

export const GET_ACCEPTED_PAWN_LIST = 'GET_ACCEPTED_PAWN_LIST';
export const PUT_ACCEPTED_PAWN_LIST = 'PUT_ACCEPTED_PAWN_LIST';

export const GET_WALLET_BALANCE = 'GET_WALLET_BALANCE';
export const PUT_WALLET_BALANCE = 'PUT_WALLET_BALANCE';

export const ADD_AMOUNT_TO_WALLET = 'ADD_AMOUNT_TO_WALLET';

export const UPDATE_PROFILE_DETAILS = 'UPDATE_PROFILE_DETAILS';
export const FAILURE_UPDATE_PROFILE = 'FAILURE_UPDATE_PROFILE';
export const SUCCESS_UPDATE_PROFILE = 'SUCCESS_UPDATE_PROFILE';
export const GET_PROFILE_DETAILS = 'GET_PROFILE_DETAILS';

export const UPLOAD_KYC = 'UPLOAD_KYC';
export const SUCCESS_UPLOADING_KYC = 'SUCCESS_UPLOADING_KYC';

export const GET_CATEGORY = 'GET_CATEGORY';
export const PUT_CATEGORY = 'PUT_CATEGORY';

export const GET_STATES = 'GET_STATES';
export const PUT_STATES = 'PUT_STATES';

export const GET_CITIES = 'GET_CITIES';
export const PUT_CITIES = 'PUT_CITIES';

export const SET_DUTY = 'SET_DUTY';
export const CONFIRM_DUTY = 'CONFIRM_DUTY';

export const GET_SUBCATEGORY = 'GET_SUBCATEGORY';
export const PUT_SUBCATEGORY = 'PUT_SUBCATEGORY';

export const GET_BUSINESSES = 'GET_BUSINESSES';
export const PUT_BUSINESSES = 'PUT_BUSINESSES';
//
export const GET_BANK_DETAILS = 'GET_BANK_DETAILS';
export const SAVE_BANK_DETAILS = 'SAVE_BANK_DETAILS';
export const SUCCESS_SAVING_BANK_DETAILS = 'SUCCESS_SAVING_BANK_DETAILS';
export const FAILURE_SAVING_BANK_DETAILS = 'FAILURE_SAVING_BANK_DETAILS';

//n2d

// export const SAVE_BUSINESS_REQUEST = 'SAVE_BUSINESS_REQUEST';
// export const SUCCESS_SAVE_BUSINESS = 'SUCCESS_SAVE_BUSINESS';
// export const FAILURE_SAVE_BUSINESS = 'FAILURE_SAVE_BUSINESS';

// export const GET_SPONSORID = 'GET_SPONSORID';
// export const PUT_SPONSORID = 'PUT_SPONSORID';

// export const GET_USERNAME = 'GET_USERNAME';
// export const PUT_USERNAME = 'PUT_USERNAME';

// export const INIT_REGISTRATION = 'INIT_REGISTRATION';
// export const SUCCESS_REGISTRATION = 'SUCCESS_REGISTRATION';
// export const FAILURE_REGISTRATION = 'FAILURE_REGISTRATION';

// export const GET_BUSINESSES_DETAILS = 'GET_BUSINESSES_DETAILS';
// export const PUT_BUSINESSES_DETAILS = 'PUT_BUSINESSES_DETAILS';

// export const SAVE_SUBSCRIPTION = 'SAVE_SUBSCRIPTION';
// export const SUBSCRIPTION_SUCCESS = 'SUBSCRIPTION_SUCCESS';

// export const UPLOAD_FILES = 'UPLOAD_FILES';
// export const UPLOAD_FILES_SUCCESS = 'UPLOAD_FILES_SUCCESS';
// export const UPLOAD_FILES_FAILURE = 'UPLOAD_FILES_FAILURE';
